branches:
  only:
  # - master
  - /^release-.*$/

language: rust # TODO: Has error with CLANG 3.9+ not being found. However CLANG 9 is installed.
rust:
  - stable

os: osx
osx_image: xcode9.4  # This is the default mac environment on travis

addons:
  homebrew:
    packages:
    - llvm
    - gmp

env:
  - NODE_VERSION="16.0" LDFLAGS="-L/usr/local/opt/llvm/lib" CPPFLAGS="-I/usr/local/opt/llvm/include"

before_install:
  - brew info llvm
  - node -v
  - nvm ls
  - nvm install $NODE_VERSION
  - node -v
  - npm install --global yarn


script:
  - cd src-tauri && cargo build
  - yarn install --frozen-lockfile
  - yarn run tauri build
  - cd /Users/travis/build/OLSF/carpe/src-tauri/target/release/bundle/dmg/ && mv carpe_0.0.1-alpha.0_x64.dmg carpe_0.0.1-alpha.0_x64-10.13.dmg
  
deploy:
  provider: releases
  api_key:
    secure: "CKC9IVRK2F7fFMtgAX8eS6JD3OmPdqaZjcMycUZIny2sVHKojEHbMKM1kjj/QZdSOCqV2CQ/oM7qZfWqAsAWJPKN2mSd4ZjvQj9HEkoisSURhif6KnSuDdQz2ff5hthU26P27+VMVe36MJNG9ajRHCk2VKiRiTI3W6M3/MVIJTyWKRYqZAqshuYIS/aVWDub+lyuBuC+KmiZ0VM6gcu4+LakDBGxcMJllIFRkYLj9/oiUppFQyxtq6gAhbf2M0+kCj0eIZTMdrKRMlDdOm/27RiKEtsiru+6HucXlIlSbYIoiFeX7Yy8P0v2zFyv00zQKA2/BLgdk3wjLWFVPZ6VkLoca+cPX7ir8zVegqNvhIhYlZMqprUifaGYY59SQZWh1Axoqap/wQIBjqqvEqRzKc4HBjTY4aOwOA8FHL+Dxi/NtbrmSML2UR5LLZV49qz9+YaiYkinVq9F2esBDNNPPdxk4iEq+fAhnIIZMUtgWMVxzBXxQPqXu5y4Q9PpUxCX8UMCcpLAvNPw4NV+P1jzjE1ifVHVBLSQBfCCcK8pbjwVLSHJOiMb/JbUBIchsUt4OXAcp1IBj+GV62kK+9ckW972LZUUZs7NsYyz+/lgjHA7akZGsPYQ8ttXWzuVdkdOghWvgrp9IIigyi/t/40tlmoxhzVaKQ/0xmHIJHghmEg="
    # TODO: This needs a differnt file name so it doesn't overwrite the other versions of Mac builds
  file: "/Users/travis/build/OLSF/carpe/src-tauri/target/release/bundle/dmg/carpe_0.0.1-alpha.0_x64.dmg"
  skip_cleanup: true
  on:
    tags: true
